# oracle-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-init
  namespace: oracle
data:
  init.sql: |
    ALTER SESSION SET CONTAINER=XEPDB1;
    
    CREATE USER TESTUSER IDENTIFIED BY testpassword;
    GRANT CONNECT, RESOURCE TO TESTUSER;
    ALTER USER TESTUSER QUOTA UNLIMITED ON USERS;
    
    GRANT CREATE SESSION TO TESTUSER;
    GRANT SELECT ON V_$DATABASE TO TESTUSER;
    GRANT FLASHBACK ANY TABLE TO TESTUSER;
    GRANT SELECT ANY TABLE TO TESTUSER;
    GRANT SELECT_CATALOG_ROLE TO TESTUSER;
    GRANT EXECUTE_CATALOG_ROLE TO TESTUSER;
    GRANT SELECT ANY TRANSACTION TO TESTUSER;
    GRANT SELECT ANY DICTIONARY TO TESTUSER;
    
    ALTER DATABASE ADD SUPPLEMENTAL LOG DATA;
    ALTER DATABASE FORCE LOGGING;
      
      -- Test table
    CREATE TABLE TESTUSER.customers (
        id NUMBER PRIMARY KEY,
        name VARCHAR2(100),
        email VARCHAR2(100),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );




