apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        image: tjdwoocn/kafka-producer-consumer-test:latest
        command: ["python", "producer_test.py"]  # Producer 스크립트 실행


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: tjdwoocn/kafka-producer-consumer-test:latest
        command: ["python", "consumer_test.py"]  # Consumer 스크립트 실행
