# 기존 Debezium Kafka Connect 이미지에서 시작
FROM debezium/connect:latest

USER root

# Oracle 커넥터와 JDBC 드라이버 복사
COPY ojdbc8.jar /kafka/connect/plugins/
COPY ojdbc8.jar /kafka/connect/debezium-connector-oracle
COPY xdb-21.15.0.0.jar /kafka/connect/plugins/
COPY xdb-21.15.0.0.jar /kafka/connect/debezium-connector-oracle



# 환경 변수 설정
ENV BOOTSTRAP_SERVERS=my-cluster-kafka-bootstrap.kafka.svc:9092
ENV GROUP_ID=connect-cluster
ENV CONFIG_STORAGE_TOPIC=connect-configs
ENV OFFSET_STORAGE_TOPIC=connect-offsets
ENV STATUS_STORAGE_TOPIC=connect-statuses
ENV CONNECT_PLUGIN_PATH=/kafka/connect/plugins
ENV CLASSPATH="/kafka/connect/plugins/ojdbc8.jar:/kafka/connect/plugins:/kafka/connect/debezium-connector-oracle/*"

# 플러그인 디렉토리 권한 설정
RUN chown -R kafka:kafka /kafka/connect/plugins
RUN chown -R kafka:kafka /kafka/connect/debezium-connector-oracle

RUN chown kafka:kafka /kafka/connect/plugins/ojdbc8.jar \
    && chown kafka:kafka /kafka/connect/debezium-connector-oracle/ojdbc8.jar \
    && chown kafka:kafka /kafka/connect/plugins/xdb-21.15.0.0.jar \
    && chown kafka:kafka /kafka/connect/debezium-connector-oracle/xdb-21.15.0.0.jar

# 작업을 마친 후 다시 kafka 사용자로 변경
USER kafka
