# Debian 기반의 이미지 사용
FROM debian:bookworm

ENV DEBIAN_FRONTEND=noninteractive

# 패키지 목록 업데이트 및 Python과 pip 설치
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    apt-get install nano && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# 작업 디렉토리 설정
WORKDIR /app

# requirements.txt 파일 복사
COPY requirements.txt ./

# 환경변수 설정
ENV KAFKA_BOOTSTRAP_SERVERS=my-cluster-kafka-bootstrap:9092

# 가상 환경 생성 및 활성화 후 필요한 라이브러리 설치
RUN python3 -m venv venv && \
    . venv/bin/activate && \
    venv/bin/pip install --no-cache-dir -r requirements.txt

# Kafka 클라이언트 코드 복사 (코드가 있는 경우)
COPY producer_sending_messages.py ./

# 기본 명령어 설정
# Python 가상환경에서 스크립트 실행  (작동이 안됨...)
# CMD ["./venv/bin/python", "producer_sending_messages.py"]
# CMD ["/app/venv/bin/python", "/app/producer_sending_messages.py"]
# ENTRYPOINT ["./venv/bin/python", "producer_sending_messages.py"]  
